titleLeft: The New
titleRight: Digital
email: hey@thenew.digital
description:
author: Maxwell Barvian
phone: (331) 215-7965

# social settings
formspree_id: xaynjygq

# build settings
source: ./src
destination: ./build
markdown: kramdown

uncss:
  stylesheets:
    - assets/css/main.css
  files:
    - "*.html"
    - "!(study)/**/*.html"
    - "study/!(questionnaire).html"
  ignore:
    - "/\\.reveal/"
    - "/\\.is-loading/"
    - "/\\.is-menu-visible/"
    - "/\\.is-transitioning/"
  timeout: 30
  
