[build]
  publish = "./build"
  command = "npm run build"
  functions = "./functions"

[build.processing]
  skip_processing = false
[build.processing.js]
  bundle = false
  minify = true
[build.processing.images]
  compress = true

[context.production]
  ENVIRONMENT = { JEKYLL_ENV = "production" }
  
[[redirects]]
  from = "/petition"
  to = "https://www.change.org/p/19355783/"
  
[[redirects]]
  from = "/donate"
  to = "https://donorbox.org/support-the-new-digital"

[[redirects]]
  from = "/podcast"
  to = "https://anchor.fm/thenewdigital"
  
[[redirects]]
 from = "*"
 to = "https://link.medium.com/J1OZLWDAX2"
 status = 302
 force = true
