[build]
  publish = "./build"
  command = "npm run build"
  functions = "./functions"

[build.processing]
  skip_processing = false
[build.processing.js]
  bundle = false
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = true

[context.production]
  ENVIRONMENT = { JEKYLL_ENV = "production" }
  
[[redirects]]
  from = "/overview"
  to = "/1"
  status = 301
  
[[redirects]]
  from = "/donate"
  to = "https://donorbox.org/support-the-new-digital"

[[redirects]]
  from = "/podcast"
  to = "https://anchor.fm/thenewdigital"
